<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
  /**
   * Seed the application's database.
   */
  public function run(): void
  {
    User::factory()->create([
      'name' => 'Admin',
      'email' => 'admin@gmail.com',
      'password' => bcrypt('admin@gmail.com'),
      'name_slug' => 'admin',
      'role' => 'admin'
    ]);

    // Foods
    $jenis = [
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Makanan',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
      'Minuman',
    ];

    $nama = [
      'Nasi Goreng Telor',
      'Nasi Goreng Ayam',
      'Nasi Goreng Kecombrang',
      'Nasi Goreng Spesial',
      'Nasi Soto Ayam',
      'Nasi Ayam Bakar',
      'Nasi Ayam Rica-Rica',
      'Nasi Ayam Geprek',
      'Capcay telor',
      'Capcay Ayam',
      'Mie Sop',
      'Mie Ayam',
      'Ifumie Binjai',
      'Burger Telor',
      'Burger Ayam',
      'Bakwan Bumbu Kacang',
      'Roti Bakar Coklat',
      'Roti Bakar Keju',
      'Pisang Coklat',
      'Pisang Keju',
      'Pisang Bakar Coklat',
      'Pisang Bakar Keju',
      'Tahu Bumbu Kacang',
      'Tahu/Tempe Mandoan',
      'Sandwich Telor',
      'Sandwich Ayam',
      'Roti Isi Ayam + Keju',
      'Salad Buah',
      'Dimsum Ayam',
      'Dimsum Udang',
      'Dimsum Rumput Laut',
      'Lumpia Kulit Tahu + F.Fries',
      'Bola-Bola Udang + F.Fries',
      'French Fries',
      'Moktail',
      'Milk Boba',
      'Matcha Yakult',
      'Kopi Hitam',
      'Kopi Susu',
      'Teh Manis',
      'Cappuchino',
      'Teh Tarik',
      'Chocolatos',
      'Lemon Tea',
      'Soda Gembira',
      'Juice',
    ];

    $gambar = [
      'img\nasgor_telor.png',
      'img\nasgor_ayam.png',
      'img\nasgor_kecombrang.png',
      'img\nasgor_spesial.png',
      'img\nasoyam.png',
      'img\nasyamkar.png',
      'img\nayamca.png',
      'img\nasyamprek.png',
      'img\caplor.png',
      'img\capyam.png',
      'img\miesop.png',
      'img\mieayam.png',
      'img\ifumiebinjai.png',
      'img\burgertelor.png',
      'img\burgerayam.png',
      'img\bakwan.png',
      'img\roticoklat.png',
      'img\rotikeju.png',
      'img\piscok.png',
      'img\pisju.png',
      'img\pisbacok.png',
      'img\pisbaju.png',
      'img\tabuka.png',
      'img\mendoan.png',
      'img\rolalor.png',
      'img\rolayam.png',
      'img\rolayamju.png',
      'img\sabu.png',
      'img\dimyam.png',
      'img\dimdang.png',
      'img\dirula.jpg',
      'img\lumkuta.png',
      'img\bodang.png',
      'img\ff.png',
      'img\moktail.png',
      'img\boba.jpg',
      'img\matcha.png',
      'img\kopihitam.png',
      'img\kopisusu.png',
      'img\tehmanis.png',
      'img\cappuchino.png',
      'img\tehtarik.png',
      'img\chocolatos.png',
      'img\lemontea.png',
      'img\sodagembira.png',
      'img\jus.png',
    ];

    $harga = [
      '12000',
      '15000',
      '17000',
      '18000',
      '16000',
      '15000',
      '15000',
      '18000',
      '15000',
      '17000',
      '12000',
      '15000',
      '17000',
      '13000',
      '15000',
      '10000',
      '10000',
      '13000',
      '10000',
      '12000',
      '10000',
      '12000',
      '10000',
      '10000',
      '13000',
      '15000',
      '17000',
      '16000',
      '15000',
      '18000',
      '18000',
      '18000',
      '18000',
      '15000',
      '10000',
      '10000',
      '10000',
      '5000',
      '8000',
      '5000',
      '8000',
      '8000',
      '8000',
      '8000',
      '8000',
      '10000',
    ];

    for ($i = 0; $i < count($nama); $i++) {
      DB::table('food')->insert([
        'name' => $nama[$i],
        'name_slug' => Str::of($nama[$i])->slug('-'),
        'jenis' => $jenis[$i],
        'image' => $gambar[$i],
        'price' => $harga[$i],
        'created_at' => now(),
        'updated_at' => now(),
      ]);
    }
  }
}
